; DrakeOS logo for mode 13h: 768-byte palette + 200x200 pixels (generated by tools/mklogo.py).
section .rodata
global logo_data
logo_data:
    incbin "drakelogo.bin"

section .note.GNU-stack noalloc noexec nowrite progbits
